#Øving 1 Oppgave 9b)
melodier=int(input("Antall ulike 10-toners melodilinjer du har hørt? "))
hort = float(melodier/(8.25*10**19))
hort_pros = float(hort*100)
print("Du har hørt "+str(hort_pros)+" prosent av melodier som er mulig.")
