#Øving 1 oppgave 4a)
x=float(input("Skriv inn et flyttall: "))
y=float(input("Skriv inn enda et flyttall: "))
z=float(input("Skriv inn et siste flyttall: "))
print("Konvertert til heltall blir det:",int(x),int(y),int(z))
a=int(input("skriv inn et heltall: "))
print("Konvertert til flyttall blir det:", float(a))
